name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
    MONGO_URI: ${{ vars.MONGO_URI }}

jobs:
    echos:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Echos
              uses: imesense/gha-echo-action@v0.2
              with:
                  input-string: ${{ vars.MONGO_URI }}
